name: Test
env:
  NODE_ENV: test

on: [push]

jobs:
  lint:
    name: Check the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get the Node version
        id: node
        run: echo "::set-output name=NODE_VERSION::$(cat .node-version)"

      - name: Setup Node ${{ steps.node.outputs.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node.outputs.NODE_VERSION }}'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --non-interactive

      - name: Run Lint
        run: yarn lint

  test:
    name: Test the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get the Node version
        id: node
        run: echo "::set-output name=NODE_VERSION::$(cat .node-version)"

      - name: Setup Node ${{ steps.node.outputs.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node.outputs.NODE_VERSION }}'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --non-interactive

      - name: Run tests
        run: yarn test
